# Generated by Django 3.1.7 on 2021-03-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210320_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
