# Generated by Django 3.1.7 on 2021-03-30 10:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210323_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='mobile',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Markspersentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Regid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
